### ISSUE TITLE
missing configs in HeavyIonsAnalysis.JetAnalysis.jets

### ISSUE THREAD

**Issue by BetterWang** [CmsHI/cmssw#273]
https://github.com/CmsHI/cmssw/blob/953dc9523f318c69ed58c81c1609337b8e8e0799/HeavyIonsAnalysis/JetAnalysis/python/fullJetSequence_pponAA_data_cff.py#L7-L15

There is no ak*_pponPbPb_data_cff.py in /src/HeavyIonsAnalysis/JetAnalysis/python/jets

These causes runForest fail.

**Comment by bi-ran** [comment]
@BetterWang 
```
cd HeavyIonsAnalysis/JetAnalysis/python/jets
./makeJetSequences.sh
```
after checking out the branch. complete instructions are here: https://twiki.cern.ch/twiki/bin/viewauth/CMS/HiForestSetup#Setup_for_10_3_X_2018_PbPb_data
